# Generated by Django 2.2.6 on 2023-10-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_bord_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='tasks.Card', verbose_name='Карточка'),
        ),
    ]
