# Generated by Django 2.2.6 on 2023-10-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_task_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='bord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
