# Generated by Django 2.2.6 on 2023-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_card_bord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AddField(
            model_name='task',
            name='same_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id'),
        ),
    ]
