# Generated by Django 2.2.6 on 2023-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20231010_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='bord',
            name='guests',
            field=models.TextField(blank=True, null=True, verbose_name='Гости'),
        ),
    ]
