# Generated by Django 2.2.6 on 2023-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_bord_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_real_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического завершения'),
        ),
        migrations.AlterField(
            model_name='bord',
            name='guests',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Гости'),
        ),
        migrations.AlterField(
            model_name='task',
            name='day_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Назначенная дата завершения'),
        ),
    ]
