# Generated by Django 2.2.6 on 2022-07-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.TextField(unique=True, verbose_name='Тип блока')),
                ('creator', models.TextField(blank=True, null=True, verbose_name='Производитель')),
                ('serial_n', models.TextField(unique=True, verbose_name='S/N')),
                ('part_n', models.TextField(verbose_name='P/N')),
                ('doc', models.FileField(blank=True, null=True, upload_to='config/монтаж/', verbose_name='Документ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ('unit_type',),
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Влож. эл. конф.')),
                ('creator', models.TextField(blank=True, null=True, verbose_name='Производитель')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='includes', to='configs.Unit', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Влож. эл. конф.',
                'verbose_name_plural': 'Влож. эл. конф.',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_n', models.TextField(verbose_name='P/N')),
                ('other_info', models.TextField(verbose_name='Проч. идент. конф.')),
                ('descr', models.TextField(verbose_name='Примечание')),
                ('doc', models.FileField(blank=True, null=True, upload_to='config/доводочные работы/', verbose_name='Документ')),
                ('number', models.IntegerField(verbose_name='номер конфигурации')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('include_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='includes', to='configs.Include', verbose_name='Влож. эл. конф.')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='configs.Unit', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Запись о конфигурации',
                'verbose_name_plural': 'Записи о конфигурации',
                'ordering': ('number',),
            },
        ),
    ]
