# Generated by Django 2.2.6 on 2022-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_remove_include_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='other_info',
            field=models.TextField(null=True, verbose_name='Проч. идент. конф.'),
        ),
    ]
