# Generated by Django 2.2.6 on 2022-08-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_numbers', to='configs.Number', verbose_name='Текущий номер конфигурации'),
        ),
    ]
