# Generated by Django 2.2.6 on 2023-05-17 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0008_auto_20220804_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametr', models.TextField(verbose_name='Параметр')),
                ('part_n', models.TextField(verbose_name='P/N')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='Проч. идент. конф.')),
                ('descr', models.TextField(verbose_name='Примечание')),
                ('doc', models.FileField(blank=True, null=True, upload_to='config/доводочные работы/', verbose_name='Документ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_users', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_numbers', to='configs.Number', verbose_name='Номер конфигурации')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_units', to='configs.Unit', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Запись о конфигурации',
                'verbose_name_plural': 'Записи о конфигурации',
                'ordering': ('number', 'unit'),
            },
        ),
    ]
