# Generated by Django 2.2.6 on 2023-05-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0009_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='author',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='pub_date',
        ),
    ]
