# Generated by Django 2.2.6 on 2023-05-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0010_auto_20230517_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametr', models.TextField(verbose_name='Параметр')),
                ('part_n', models.TextField(verbose_name='P/N')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name='Проч. идент. конф.')),
                ('descr', models.TextField(verbose_name='Примечание')),
                ('doc', models.FileField(blank=True, null=True, upload_to='config/доводочные работы/', verbose_name='Документ')),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chs_numbers', to='configs.Number', verbose_name='Номер конфигурации')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chs_units', to='configs.Unit', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Запись о изменении',
                'verbose_name_plural': 'Записи о изменениях',
                'ordering': ('number', 'unit'),
            },
        ),
    ]
