# Generated by Django 2.2.6 on 2023-05-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0013_auto_20230519_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changes',
            options={'ordering': ('number', 'unit', 'id'), 'verbose_name': 'Запись о изменении', 'verbose_name_plural': 'Записи о изменениях'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('id',), 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
