# Generated by Django 2.2.6 on 2023-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0014_auto_20230527_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
