# Generated by Django 2.2.6 on 2023-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0015_unit_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Позация'),
        ),
    ]
