# Generated by Django 2.2.6 on 2023-08-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0016_unit_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pos_on_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позация на кладе'),
        ),
    ]
