# Generated by Django 2.2.6 on 2021-06-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
