# Generated by Django 2.2.6 on 2021-06-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
