# Generated by Django 2.2.6 on 2021-06-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.State', verbose_name='Статус'),
        ),
    ]
