# Generated by Django 2.2.6 on 2021-06-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210616_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('state',)},
        ),
    ]
