# Generated by Django 2.2.6 on 2021-06-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210616_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='posts.State', verbose_name='Статус'),
        ),
    ]
