# Generated by Django 2.2.6 on 2021-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210617_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.CharField(max_length=200, verbose_name='Статус задачи')),
            ],
            options={
                'ordering': ('task_state',),
            },
        ),
    ]
