# Generated by Django 2.2.6 on 2021-06-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_task_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
