# Generated by Django 2.2.6 on 2021-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210623_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата испытаний'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_start',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='время начала'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_stop',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='время начала'),
        ),
    ]
