# Generated by Django 2.2.6 on 2021-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210812_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_start',
            field=models.TextField(blank=True, default=8, null=True, verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stop',
            field=models.TextField(blank=True, default=18, null=True, verbose_name='время начала'),
        ),
    ]
