# Generated by Django 2.2.6 on 2021-08-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210812_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Номер отдела')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отдела')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='add_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные требования'),
        ),
        migrations.AddField(
            model_name='post',
            name='configuration',
            field=models.TextField(blank=True, null=True, verbose_name='Минимальная конфигурация стенда'),
        ),
        migrations.AddField(
            model_name='post',
            name='instruments',
            field=models.TextField(blank=True, null=True, verbose_name='Необходимый инструмент'),
        ),
        migrations.AddField(
            model_name='post',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Цель проведения испытаний'),
        ),
        migrations.AddField(
            model_name='post',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Основания для проведения испытаний'),
        ),
        migrations.AddField(
            model_name='post',
            name='test_object',
            field=models.TextField(blank=True, null=True, verbose_name='Объект испытаний'),
        ),
        migrations.AddField(
            model_name='post',
            name='testers',
            field=models.TextField(blank=True, null=True, verbose_name='Состав бригады испытателей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_start',
            field=models.TextField(default=8, verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stop',
            field=models.TextField(default=18, verbose_name='время начала'),
        ),
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='posts.Unit', verbose_name='Подразделение - инициатор'),
        ),
    ]
