# Generated by Django 2.2.6 on 2021-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210813_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('title',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stop',
            field=models.TextField(default=18, verbose_name='время окончания'),
        ),
    ]
