# Generated by Django 2.2.6 on 2021-08-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20210813_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-day',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
