# Generated by Django 2.2.6 on 2021-08-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20210813_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='posts.Task_state', verbose_name='Статус'),
        ),
    ]
