# Generated by Django 2.2.6 on 2021-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20210816_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lol',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные требования'),
        ),
    ]
