# Generated by Django 2.2.6 on 2021-08-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_remove_post_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='task_state',
        ),
    ]
