# Generated by Django 2.2.6 on 2021-08-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_post_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='task_state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='posts.Task_state', verbose_name='Статус'),
        ),
    ]
