# Generated by Django 2.2.6 on 2021-08-16 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20210816_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 17, 9, 15, 246720), null=True, verbose_name='Дата испытаний'),
        ),
    ]
