# Generated by Django 2.2.6 on 2021-08-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20210819_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(unique=True, verbose_name='Номер заявки'),
        ),
    ]
