# Generated by Django 2.2.6 on 2021-08-27 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20210827_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='t_start',
        ),
        migrations.AddField(
            model_name='post',
            name='t_start',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='posts.Time', verbose_name='время начала'),
        ),
        migrations.AddField(
            model_name='post',
            name='t_stop',
            field=models.ForeignKey(blank=True, default=18, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='posts.Time', verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
    ]
