# Generated by Django 2.2.6 on 2021-08-30 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20210827_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_stop',
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 8, 30), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_start',
            field=models.ForeignKey(blank=True, default=3, help_text='время начала испытаний должно быть строго меньше времени завершения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='posts.Time', verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_stop',
            field=models.ForeignKey(blank=True, default=21, help_text='время завершения испытаний должно быть строго больше времени начала', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='posts.Time', verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='номер заявки присваивается автоматически в порядке возрастания', verbose_name='Номер заявки'),
        ),
    ]
