# Generated by Django 2.2.6 on 2021-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20210830_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='номер заявки присваивается автоматически в порядке возрастания', unique=True, verbose_name='Номер заявки'),
        ),
    ]
