# Generated by Django 2.2.6 on 2021-09-09 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20210907_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='percent',
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 9, 9), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
    ]
