# Generated by Django 2.2.6 on 2021-09-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20210909_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-day', '-text'), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
