# Generated by Django 2.2.6 on 2021-10-05 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_auto_20211004_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='doc',
            field=models.TextField(blank=True, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 10, 5), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
    ]
