# Generated by Django 2.2.6 on 2021-10-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20211005_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 10, 7), null=True, verbose_name='Дата испытаний'),
        ),
    ]
