# Generated by Django 2.2.6 on 2021-10-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_auto_20211007_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2021, 10, 13), verbose_name='Дата испытаний'),
        ),
    ]
