# Generated by Django 2.2.6 on 2021-10-14 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_auto_20211013_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2021, 10, 14), verbose_name='Дата испытаний'),
        ),
    ]
