# Generated by Django 2.2.6 on 2021-10-15 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_auto_20211014_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2021, 10, 15), verbose_name='Дата испытаний'),
        ),
    ]
