# Generated by Django 2.2.6 on 2021-10-21 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_auto_20211015_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('title',), 'verbose_name': 'Стенд', 'verbose_name_plural': 'Стенды'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='creat',
        ),
        migrations.RemoveField(
            model_name='group',
            name='descrip_slug',
        ),
        migrations.RemoveField(
            model_name='group',
            name='step',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tu',
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание стенда'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название стенда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2021, 10, 21), verbose_name='Дата испытаний'),
        ),
    ]
