# Generated by Django 2.2.6 on 2022-03-15 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_auto_20211118_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='configuration',
            field=models.TextField(verbose_name='Минимальная конфигурация стенда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2022, 3, 15), verbose_name='Дата испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='purpose',
            field=models.TextField(verbose_name='Цель проведения испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reason',
            field=models.TextField(verbose_name='Основания для проведения испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_start',
            field=models.ForeignKey(default=3, help_text='время начала испытаний должно быть строго меньше времени завершения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='posts.Time', verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_stop',
            field=models.ForeignKey(default=21, help_text='время завершения испытаний должно быть строго больше времени начала', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='posts.Time', verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='test_object',
            field=models.TextField(verbose_name='Объект испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='testers',
            field=models.TextField(verbose_name='Состав бригады испытателей'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='posts.Unit', verbose_name='Подразделение - инициатор'),
        ),
    ]
