# Generated by Django 2.2.6 on 2022-03-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_auto_20220317_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2022, 3, 18), verbose_name='Дата испытаний'),
        ),
    ]
