# Generated by Django 2.2.6 on 2022-04-06 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_auto_20220404_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2022, 4, 6), verbose_name='Дата испытаний'),
        ),
    ]
