# Generated by Django 2.2.6 on 2022-04-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_auto_20220406_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2022, 4, 8), verbose_name='Дата испытаний'),
        ),
    ]
