# Generated by Django 2.2.6 on 2022-06-24 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0066_auto_20220411_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата испытаний'),
        ),
    ]
