# Generated by Django 2.2.6 on 2022-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_auto_20220624_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='all_in',
            field=models.TextField(blank=True, null=True, verbose_name='Стенды в заявке'),
        ),
    ]
