# Generated by Django 2.2.6 on 2022-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_auto_20220720_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='media/posts/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='unswer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
