# Generated by Django 2.2.6 on 2022-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0070_auto_20220721_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['state_id'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='post',
            name='configuration',
            field=models.TextField(blank=True, null=True, verbose_name='Минимальная конфигурация стенда'),
        ),
        migrations.AlterField(
            model_name='post',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Цель проведения испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Основания для проведения испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='test_object',
            field=models.TextField(blank=True, null=True, verbose_name='Объект испытаний'),
        ),
        migrations.AlterField(
            model_name='post',
            name='testers',
            field=models.TextField(blank=True, null=True, verbose_name='Состав бригады испытателей'),
        ),
    ]
