# Generated by Django 2.2.6 on 2022-11-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0072_auto_20221122_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='unswer',
            field=models.TextField(blank=True, default='Нет ответа', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_start',
            field=models.ForeignKey(default=17, help_text='если время начала испытаний больше времени завершения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='posts.Time', verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_stop',
            field=models.ForeignKey(default=27, help_text='то заявка завершится в следующем дне', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='posts.Time', verbose_name='время окончания'),
        ),
    ]
