# Generated by Django 2.2.6 on 2022-12-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0073_auto_20221127_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_state',
            options={'ordering': ('task_state',), 'verbose_name': 'Статус задачи или обращения', 'verbose_name_plural': 'Статусы задач и обращений'},
        ),
        migrations.AddField(
            model_name='task_state',
            name='state_descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание статуса'),
        ),
    ]
