# Generated by Django 2.2.6 on 2022-12-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0074_auto_20221205_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Дизлайк', 'verbose_name_plural': 'Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
