# Generated by Django 2.2.6 on 2023-07-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0075_auto_20221216_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='t_start',
            field=models.ForeignKey(default=17, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time', to='posts.Time', verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_stop',
            field=models.ForeignKey(default=27, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='times', to='posts.Time', verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(unique=True, verbose_name='Номер заявки'),
        ),
    ]
