# Generated by Django 2.2.6 on 2023-12-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0076_auto_20230719_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.DateTimeField(default=datetime.date(2023, 12, 5), verbose_name='Дата испытаний'),
        ),
    ]
