# Generated by Django 2.2.6 on 2024-04-23 11:53

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0078_auto_20240115_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to=posts.models.rename_file, verbose_name='Картинка'),
        ),
    ]
