# Generated by Django 2.2.19 on 2022-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(verbose_name='Номер')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('name', models.TextField(verbose_name='Имя')),
                ('sec_name', models.TextField(verbose_name='Фамилия')),
                ('patro', models.TextField(verbose_name='Отчество')),
                ('pasport', models.TextField(verbose_name='Паспорт')),
                ('trans', models.TextField(verbose_name='Провоз на авто')),
                ('auto', models.TextField(verbose_name='Марка и молель авто')),
                ('num_auto', models.TextField(verbose_name='Номер авто')),
                ('stuff', models.TextField(verbose_name='Провозимое имущество')),
                ('quantity', models.TextField(verbose_name='Количество')),
                ('day', models.DateTimeField(blank=True, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField(verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Пропуск на машину',
                'verbose_name_plural': 'Пропуска на машину',
                'ordering': ('num',),
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(verbose_name='Номер')),
                ('name', models.TextField(verbose_name='Имя')),
                ('sec_name', models.TextField(verbose_name='Фамилия')),
                ('patro', models.TextField(verbose_name='Отчество')),
                ('where', models.TextField(verbose_name='Откуда')),
                ('day', models.DateTimeField(blank=True, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField(verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуска',
                'ordering': ('num',),
            },
        ),
    ]
