# Generated by Django 2.2.19 on 2022-10-11 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата'),
        ),
    ]
