# Generated by Django 2.2.6 on 2022-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_auto_20221011_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='pasport',
            field=models.TextField(default=1, verbose_name='Паспорт'),
            preserve_default=False,
        ),
    ]
