# Generated by Django 2.2.6 on 2022-10-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0006_auto_20221018_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 11, 26, 15, 308929), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата'),
        ),
    ]
