# Generated by Django 2.2.6 on 2022-10-19 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0009_auto_20221019_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 10, 13, 43, 878521), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата'),
        ),
    ]
