# Generated by Django 2.2.6 on 2022-11-22 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0014_auto_20221021_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ('-day', '-num'), 'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 9, 50, 47, 73989), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата'),
        ),
    ]
