# Generated by Django 2.2.6 on 2022-11-27 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0015_auto_20221122_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='passes/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 9, 6, 41, 209926, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='car_pass',
            name='pasport',
            field=models.TextField(help_text='формат ввода: XXXX XXXXXX', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 12, 6, 41, 208926), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pasport',
            field=models.TextField(help_text='формат ввода: XXXX XXXXXX', verbose_name='Паспорт'),
        ),
    ]
