# Generated by Django 2.2.6 on 2022-11-29 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0016_auto_20221127_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='doc_type',
            field=models.TextField(blank=True, default='Паспорт', null=True, verbose_name='Документ, удостоверяющий личность'),
        ),
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 8, 17, 8, 256493, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 17, 8, 256493), verbose_name='Дата'),
        ),
    ]
