# Generated by Django 2.2.6 on 2022-11-29 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0017_auto_20221129_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='spec',
            field=models.TextField(blank=True, default='Мыльников', null=True, verbose_name='Подписант'),
        ),
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 8, 24, 29, 307031, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 24, 29, 306031), verbose_name='Дата'),
        ),
    ]
