# Generated by Django 2.2.6 on 2022-12-05 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0021_auto_20221202_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 12, 43, 20, 317085, tzinfo=utc), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 15, 43, 20, 316085), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='spec',
            field=models.TextField(blank=True, choices=[('Д.А. Мыльников', 'Д.А. Мыльников'), ('Л.А. Елагин', 'Л.А. Елагин'), ('С.А. Осипенко', 'С.А. Осипенко')], default='Д.А. Мыльников', null=True, verbose_name='Подписант'),
        ),
    ]
