# Generated by Django 2.2.6 on 2022-12-16 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0023_auto_20221205_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 16, 9, 27, 0, 154601), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 9, 27, 0, 154601), verbose_name='Дата'),
        ),
    ]
