# Generated by Django 2.2.6 on 2023-01-17 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0025_auto_20230117_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 17, 15, 40, 57, 91617), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 15, 40, 57, 90616), verbose_name='Дата'),
        ),
    ]
