# Generated by Django 2.2.6 on 2023-02-05 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0035_auto_20230201_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 22, 27, 27, 183245), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 27, 27, 183245), verbose_name='Дата'),
        ),
    ]
