# Generated by Django 2.2.6 on 2023-02-21 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0044_auto_20230221_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 9, 40, 22, 408865), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 9, 40, 22, 407865), verbose_name='Дата'),
        ),
    ]
