# Generated by Django 2.2.6 on 2023-04-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0053_auto_20230227_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 24, 14, 26, 31, 763967), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 14, 26, 31, 762967), verbose_name='Дата'),
        ),
    ]
