# Generated by Django 2.2.6 on 2023-04-25 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0055_auto_20230425_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 16, 39, 48, 618503), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 16, 39, 48, 618503), verbose_name='Дата'),
        ),
    ]
