# Generated by Django 2.2.6 on 2023-07-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0071_auto_20230719_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 19, 15, 18, 49, 34767), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 15, 18, 49, 33767), verbose_name='Дата'),
        ),
    ]
