# Generated by Django 2.2.6 on 2023-07-26 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0074_auto_20230726_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 26, 10, 44, 33, 69819), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 10, 44, 33, 69819), verbose_name='Дата'),
        ),
    ]
