# Generated by Django 2.2.6 on 2023-08-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0075_auto_20230726_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 8, 12, 47, 59, 332586), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 12, 47, 59, 331586), verbose_name='Дата'),
        ),
    ]
