# Generated by Django 2.2.6 on 2023-08-28 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0077_auto_20230817_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 11, 54, 33, 732596), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 11, 54, 33, 732596), verbose_name='Дата'),
        ),
    ]
