# Generated by Django 2.2.6 on 2023-10-09 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0085_auto_20231006_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 9, 14, 52, 8, 103392), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 14, 52, 8, 102393), verbose_name='Дата'),
        ),
    ]
