# Generated by Django 2.2.6 on 2023-10-09 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0087_auto_20231009_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 9, 14, 57, 17, 104769), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 14, 57, 17, 103770), verbose_name='Дата'),
        ),
    ]
