# Generated by Django 2.2.6 on 2023-10-10 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0090_auto_20231010_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 16, 2, 35, 555467), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 16, 2, 35, 555467), verbose_name='Дата'),
        ),
    ]
