# Generated by Django 2.2.6 on 2023-11-02 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0099_auto_20231101_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 2, 15, 5, 38, 188720), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 15, 5, 38, 186721), verbose_name='Дата'),
        ),
    ]
