# Generated by Django 2.2.6 on 2023-11-14 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0100_auto_20231102_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 14, 10, 22, 50, 173454), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 10, 22, 50, 172455), verbose_name='Дата'),
        ),
    ]
