# Generated by Django 2.2.6 on 2023-12-04 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0105_auto_20231204_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 9, 13, 25, 391951), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 9, 13, 25, 390951), verbose_name='Дата'),
        ),
    ]
