# Generated by Django 2.2.6 on 2024-01-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0110_auto_20231205_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 15, 9, 58, 22, 120515), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 9, 58, 22, 119516), verbose_name='Дата'),
        ),
    ]
