# Generated by Django 2.2.6 on 2024-04-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0115_auto_20240423_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 16, 9, 30, 626300), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 16, 9, 30, 626300), verbose_name='Дата'),
        ),
    ]
