# Generated by Django 2.2.6 on 2024-05-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0120_auto_20240517_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 17, 13, 50, 44, 384228), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 13, 50, 44, 384228), verbose_name='Дата'),
        ),
    ]
