# Generated by Django 2.2.6 on 2024-05-30 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0125_auto_20240530_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 30, 16, 28, 29, 136815), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 16, 28, 29, 135815), verbose_name='Дата'),
        ),
    ]
