# Generated by Django 2.2.6 on 2024-06-22 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0128_auto_20240531_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 22, 21, 33, 5, 827613), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 21, 33, 5, 826614), verbose_name='Дата'),
        ),
    ]
