# Generated by Django 2.2.6 on 2024-06-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0129_auto_20240622_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 23, 16, 16, 25, 35744), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 23, 16, 16, 25, 34745), verbose_name='Дата'),
        ),
    ]
