# Generated by Django 2.2.6 on 2023-12-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Доска')),
                ('guests', models.TextField(blank=True, default='', null=True, verbose_name='Гости')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bords', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Карточка')),
                ('bord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bord_cards', to='tasks.Bord', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Task_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.CharField(max_length=200, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Статус задачи или обращения',
                'verbose_name_plural': 'Статусы задач и обращений',
                'ordering': ('task_state',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('persent', models.IntegerField(blank=True, null=True, verbose_name='%')),
                ('include_in', models.IntegerField(blank=True, null=True, verbose_name='входит в задачу №')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ')),
                ('day_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала')),
                ('day_end', models.DateTimeField(blank=True, null=True, verbose_name='Назначенная дата завершения')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('same_id', models.IntegerField(blank=True, null=True, verbose_name='id')),
                ('day_real_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического завершения')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='tasks.Card', verbose_name='Карточка')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('state', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='tasks.Task_state', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('master',),
            },
        ),
    ]
