# Generated by Django 2.2.6 on 2024-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-day_update',), 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AddField(
            model_name='note',
            name='same_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id'),
        ),
    ]
