# Generated by Django 2.2.6 on 2024-05-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20240423_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bord_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_bord', to='tasks.Bord', verbose_name='ссылка на доску задачи'),
        ),
    ]
