# Generated by Django 2.2.6 on 2024-05-30 07:54

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_bord_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to=tasks.models.rename_file, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.rename_file, verbose_name='Документ'),
        ),
    ]
