# Generated by Django 2.2.6 on 2024-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20240530_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новая задача или нет'),
        ),
    ]
