# Generated by Django 2.2.6 on 2024-05-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_bord', to='tasks.Bord', verbose_name='принадлежность к доске'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bord_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_bord_link', to='tasks.Bord', verbose_name='ссылка на доску задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='new',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Новая задача или нет'),
        ),
    ]
