# Generated by Django 2.2.6 on 2023-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_unswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='same_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id вопроса'),
        ),
    ]
