# Generated by Django 2.2.6 on 2023-02-05 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230205_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 22, 53, 52, 194833), null=True, verbose_name='Дата'),
        ),
    ]
