# Generated by Django 2.2.6 on 2023-02-13 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230213_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 13, 11, 5, 49, 508104), null=True, verbose_name='Дата'),
        ),
    ]
