# Generated by Django 2.2.6 on 2023-02-21 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230221_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 11, 39, 17, 126510), null=True, verbose_name='Дата'),
        ),
    ]
