# Generated by Django 2.2.6 on 2023-02-21 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_auto_20230221_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 17, 30, 35, 225109), null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 17, 30, 35, 225109), null=True, verbose_name='Дата начала')),
                ('day_end', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 17, 30, 35, 225109), null=True, verbose_name='Дата окончания')),
                ('year', models.TextField(blank=True, null=True, verbose_name='Период')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'ordering': ('-user',),
            },
        ),
    ]
