# Generated by Django 2.2.6 on 2023-02-21 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230221_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='how_long',
            field=models.TextField(blank=True, null=True, verbose_name='Всего дней'),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 18, 0, 55, 848153), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='day_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='day_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='year',
            field=models.TextField(blank=True, choices=[('2023', '2023'), ('2024', '2024')], null=True, verbose_name='Период'),
        ),
    ]
