# Generated by Django 2.2.6 on 2023-04-25 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230424_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 25, 16, 38, 57, 420503), null=True, verbose_name='Дата'),
        ),
    ]
