# Generated by Django 2.2.6 on 2023-05-17 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20230517_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 17, 17, 31, 14, 374166), null=True, verbose_name='Дата'),
        ),
    ]
