# Generated by Django 2.2.6 on 2023-05-27 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20230527_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 27, 21, 26, 31, 778065), null=True, verbose_name='Дата'),
        ),
    ]
