# Generated by Django 2.2.6 on 2023-07-26 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20230719_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 26, 10, 41, 50, 328819), null=True, verbose_name='Дата'),
        ),
    ]
