# Generated by Django 2.2.6 on 2023-08-28 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20230817_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 11, 54, 33, 711596), null=True, verbose_name='Дата'),
        ),
    ]
