# Generated by Django 2.2.6 on 2023-08-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20230830_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 14, 41, 10, 781233), null=True, verbose_name='Дата'),
        ),
    ]
