# Generated by Django 2.2.6 on 2023-08-30 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20230830_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 30, 14, 50, 19, 801130), null=True, verbose_name='Дата'),
        ),
    ]
