# Generated by Django 2.2.6 on 2023-10-04 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20230830_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 4, 14, 32, 22, 168281), null=True, verbose_name='Дата'),
        ),
    ]
