# Generated by Django 2.2.6 on 2023-10-04 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20231004_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 4, 15, 45, 19, 493739), null=True, verbose_name='Дата'),
        ),
    ]
