# Generated by Django 2.2.6 on 2023-10-06 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20231004_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 6, 12, 0, 39, 514698), null=True, verbose_name='Дата'),
        ),
    ]
