# Generated by Django 2.2.6 on 2023-10-09 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20231006_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 9, 14, 52, 8, 91397), null=True, verbose_name='Дата'),
        ),
    ]
