# Generated by Django 2.2.6 on 2023-10-09 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20231009_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 9, 14, 53, 51, 866259), null=True, verbose_name='Дата'),
        ),
    ]
