# Generated by Django 2.2.6 on 2023-10-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20231009_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 9, 14, 59, 30, 528813), null=True, verbose_name='Дата'),
        ),
    ]
