# Generated by Django 2.2.6 on 2023-10-10 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20231009_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 13, 2, 27, 365865), null=True, verbose_name='Дата'),
        ),
    ]
