# Generated by Django 2.2.6 on 2023-10-10 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20231010_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 16, 2, 35, 541476), null=True, verbose_name='Дата'),
        ),
    ]
