# Generated by Django 2.2.6 on 2023-10-23 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20231010_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='can_redact',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Возможность редактировать'),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 23, 14, 57, 26, 46135), null=True, verbose_name='Дата'),
        ),
    ]
