# Generated by Django 2.2.6 on 2023-11-01 08:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0062_auto_20231023_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 11, 19, 29, 971534), null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='User_widgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Заявки на испытания')),
                ('vacs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отпуска')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к виджетам',
                'ordering': ('user',),
            },
        ),
    ]
