# Generated by Django 2.2.6 on 2023-11-01 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20231101_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='bibl_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к библиотеке'),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 12, 57, 14, 563091), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='test_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к тестам'),
        ),
    ]
