# Generated by Django 2.2.6 on 2023-11-01 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0068_auto_20231101_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 1, 16, 13, 6, 52252), null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Номер заявки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_one_mess', to=settings.AUTH_USER_MODEL, verbose_name='Первый пользователь')),
                ('user_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_two_mess', to=settings.AUTH_USER_MODEL, verbose_name='Второй пользователь')),
                ('witch_write', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_witch_write', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь который написал')),
            ],
            options={
                'verbose_name': 'Переписка',
                'ordering': ('pub_date',),
            },
        ),
    ]
