# Generated by Django 2.2.6 on 2023-11-14 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20231102_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 14, 10, 22, 50, 159461), null=True, verbose_name='Дата'),
        ),
    ]
