# Generated by Django 2.2.6 on 2023-12-04 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20231114_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 9, 1, 43, 701562), null=True, verbose_name='Дата'),
        ),
    ]
