# Generated by Django 2.2.6 on 2023-12-04 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20231204_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 4, 9, 13, 25, 363968), null=True, verbose_name='Дата'),
        ),
    ]
