# Generated by Django 2.2.6 on 2023-02-06 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='day',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='block',
            name='on_control',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вх. контроль'),
        ),
        migrations.AddField(
            model_name='block',
            name='on_fix',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отремонтированно'),
        ),
        migrations.AddField(
            model_name='block',
            name='on_fix_developer',
            field=models.BooleanField(blank=True, null=True, verbose_name='В ремонте у поставщика'),
        ),
    ]
