# Generated by Django 2.2.6 on 2023-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20230206_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='on_ready',
            field=models.BooleanField(blank=True, null=True, verbose_name='Изготовлен'),
        ),
    ]
