# Generated by Django 2.2.6 on 2023-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_block_on_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='block',
            name='day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
