# Generated by Django 2.2.6 on 2023-02-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20230207_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('day', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.TextField(unique=True, verbose_name='Номер блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='on_fix',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отремонтирован'),
        ),
        migrations.AlterField(
            model_name='block',
            name='on_injector',
            field=models.BooleanField(blank=True, null=True, verbose_name='В изоляторе'),
        ),
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200, verbose_name='Тип события')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='pro.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_events', to='pro.Block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_event', to='pro.Event_type', verbose_name='Тип события'),
        ),
    ]
