# Generated by Django 2.2.6 on 2023-02-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_remove_event_type_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_state', models.CharField(max_length=200, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='block',
            name='block_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_states', to='pro.Block_state', verbose_name='Статус блока'),
        ),
    ]
