# Generated by Django 2.2.6 on 2023-02-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_auto_20230220_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='on_control',
        ),
        migrations.RemoveField(
            model_name='block',
            name='on_fix',
        ),
        migrations.RemoveField(
            model_name='block',
            name='on_fix_developer',
        ),
        migrations.RemoveField(
            model_name='block',
            name='on_injector',
        ),
        migrations.RemoveField(
            model_name='block',
            name='on_storage',
        ),
        migrations.AlterField(
            model_name='event',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_events', to='pro.Block', verbose_name='Блок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_event', to='pro.Event_type', verbose_name='Тип события'),
            preserve_default=False,
        ),
    ]
