# Generated by Django 2.2.6 on 2023-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_auto_20230221_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_state_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего статуса'),
        ),
    ]
