# Generated by Django 2.2.6 on 2023-01-17 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otd_number', models.IntegerField(blank=True, null=True, verbose_name='Номер отдела')),
                ('reqs_access', models.BooleanField(blank=True, default=True, null=True, verbose_name='Доступ к заявкам')),
                ('pass_access', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к пропускам')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_info', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
                'ordering': ('boss',),
            },
        ),
    ]
