# Generated by Django 2.2.6 on 2023-01-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230117_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='conf_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к конфигурации'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='corr_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к корреспонденции'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='stor_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к складу'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='task_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к задачам'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к сотрудникам'),
        ),
    ]
