# Generated by Django 2.2.6 on 2023-02-01 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20230118_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('event', models.TextField(blank=True, null=True, verbose_name='Событие')),
                ('res', models.TextField(blank=True, null=True, verbose_name='Ресурс')),
                ('before', models.TextField(blank=True, null=True, verbose_name='До изменений')),
                ('after', models.TextField(blank=True, null=True, verbose_name='После изменений')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'ordering': ('day',),
            },
        ),
    ]
