# Generated by Django 2.2.6 on 2023-02-05 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-day',), 'verbose_name': 'Запись'},
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 22, 27, 27, 174273), null=True, verbose_name='Дата'),
        ),
    ]
