# Generated by Django 2.2.6 on 2023-02-07 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230206_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 11, 6, 43, 339006), null=True, verbose_name='Дата'),
        ),
    ]
