# Generated by Django 2.2.6 on 2023-02-27 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230221_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ('user', 'day_start'), 'verbose_name': 'Отпуск'},
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 9, 32, 23, 935248), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='year',
            field=models.TextField(blank=True, null=True, verbose_name='Период'),
        ),
    ]
