# Generated by Django 2.2.6 on 2023-05-17 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20230510_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 17, 16, 56, 48, 478597), null=True, verbose_name='Дата'),
        ),
    ]
