# Generated by Django 2.2.6 on 2023-05-19 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20230518_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 11, 49, 4, 594602), null=True, verbose_name='Дата'),
        ),
    ]
