# Generated by Django 2.2.6 on 2023-05-19 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20230519_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 19, 17, 3, 6, 95602), null=True, verbose_name='Дата'),
        ),
    ]
