# Generated by Django 2.2.6 on 2023-05-30 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20230527_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 30, 9, 50, 36, 71666), null=True, verbose_name='Дата'),
        ),
    ]
