# Generated by Django 2.2.6 on 2023-07-19 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20230719_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 19, 15, 13, 13, 534783), null=True, verbose_name='Дата'),
        ),
    ]
