# Generated by Django 2.2.6 on 2023-07-26 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20230719_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 26, 11, 29, 14, 580259), null=True, verbose_name='Дата'),
        ),
    ]
