# Generated by Django 2.2.6 on 2023-10-06 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20230817_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 6, 13, 25, 15, 125757), null=True, verbose_name='Дата'),
        ),
    ]
