# Generated by Django 2.2.6 on 2023-11-08 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20231006_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='can_redact',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Возможность редактировать'),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 8, 11, 42, 1, 284263), null=True, verbose_name='Дата'),
        ),
    ]
