# Generated by Django 2.2.6 on 2024-01-15 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20231121_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 15, 10, 7, 19, 753669), null=True, verbose_name='Дата'),
        ),
    ]
