# Generated by Django 2.2.6 on 2024-04-23 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20240115_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 14, 53, 57, 546988), null=True, verbose_name='Дата'),
        ),
    ]
