# Generated by Django 2.2.6 on 2024-04-23 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20240423_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 15, 33, 20, 714633), null=True, verbose_name='Дата'),
        ),
    ]
