# Generated by Django 2.2.6 on 2024-04-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20240423_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 16, 9, 30, 616307), null=True, verbose_name='Дата'),
        ),
    ]
