# Generated by Django 2.2.6 on 2024-05-14 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20240513_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 16, 36, 55, 699236), null=True, verbose_name='Дата'),
        ),
    ]
