# Generated by Django 2.2.6 on 2024-05-17 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20240517_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='mess_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к мессенджеру'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='news_access',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Доступ к новостям'),
        ),
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 17, 13, 23, 48, 918688), null=True, verbose_name='Дата'),
        ),
    ]
