# Generated by Django 2.2.6 on 2024-05-31 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20240531_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 31, 14, 41, 33, 450130), null=True, verbose_name='Дата'),
        ),
    ]
