# Generated by Django 2.2.6 on 2024-06-23 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20240622_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 23, 16, 16, 25, 25716), null=True, verbose_name='Дата'),
        ),
    ]
