# Generated by Django 2.2.6 on 2021-08-30 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название производителя')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Ctgry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Место хранения')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание производителя')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Si',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Еденицы измерения')),
            ],
            options={
                'verbose_name': 'Еденицы измерения',
                'verbose_name_plural': 'Еденицы измерения',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='th',
            options={'ordering': ('-day',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='unit',
            name='author',
            field=models.TextField(default=1, verbose_name='Кто добавил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 8, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='cz',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Служебная записка'),
        ),
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.TextField(default=datetime.date(2021, 8, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='storage.Unit', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='th',
            name='th',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Накладная'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to='storage.Creator', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ctgry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctgrys', to='storage.Ctgry', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='storage.Place', verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sis', to='storage.Si', verbose_name='Еденицы измерения'),
        ),
    ]
