# Generated by Django 2.2.6 on 2021-08-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20210831_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='pub_day',
        ),
    ]
