# Generated by Django 2.2.6 on 2021-08-31 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_unit_pub_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 8, 31), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.TextField(default=datetime.date(2021, 8, 31), verbose_name='Дата'),
        ),
    ]
