# Generated by Django 2.2.6 on 2021-08-31 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210831_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='th',
            name='author',
            field=models.TextField(default=1, verbose_name='Кто добавил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 8, 31), verbose_name='Дата'),
        ),
    ]
