# Generated by Django 2.2.6 on 2021-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210831_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th',
            name='cz',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Служебная записка'),
        ),
        migrations.AlterField(
            model_name='th',
            name='th',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Накладная'),
        ),
    ]
