# Generated by Django 2.2.6 on 2021-09-06 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20210904_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.TextField(default=datetime.date(2021, 9, 6), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 6), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 6), verbose_name='Дата'),
        ),
    ]
