# Generated by Django 2.2.6 on 2021-09-07 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20210906_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctgry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='si',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание ед. изм.'),
        ),
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 9, 7), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
        migrations.AlterField(
            model_name='th',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='storage.Unit', verbose_name='Учетная единица'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 7), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='title',
            field=models.TextField(verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 7), verbose_name='Дата'),
        ),
    ]
