# Generated by Django 2.2.6 on 2021-09-09 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20210907_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('pk',), 'verbose_name': 'Место хранения', 'verbose_name_plural': 'Места хранения'},
        ),
        migrations.AlterField(
            model_name='creator',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='ctgry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='si',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='si',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 9, 9), help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата испытаний'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 9), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2021, 9, 9), verbose_name='Дата'),
        ),
    ]
