# Generated by Django 2.2.6 on 2022-08-04 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_auto_20220721_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 8, 4), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 8, 4), verbose_name='Дата'),
        ),
    ]
