# Generated by Django 2.2.6 on 2022-09-28 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_auto_20220804_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.TextField(verbose_name='Тип')),
            ],
        ),
        migrations.RemoveField(
            model_name='th',
            name='name',
        ),
        migrations.AlterField(
            model_name='th',
            name='day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 9, 28), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 9, 28), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(verbose_name='Количество')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_day', models.TextField(default=datetime.date(2022, 9, 28), verbose_name='Дата')),
                ('author', models.TextField(verbose_name='Кто добавил')),
                ('event_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='storage.Type_event', verbose_name='Событие')),
                ('th_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ths', to='storage.Th', verbose_name='Накладная')),
                ('unit_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='storage.Unit', verbose_name='Учетная единица')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('-date',),
            },
        ),
    ]
