# Generated by Django 2.2.6 on 2022-10-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_auto_20220928_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stend',
            options={'ordering': ('pk',), 'verbose_name': 'Стенд', 'verbose_name_plural': 'Стенды'},
        ),
        migrations.AlterModelOptions(
            name='th',
            options={'ordering': ('-day',), 'verbose_name': 'Накладная', 'verbose_name_plural': 'Накладные'},
        ),
        migrations.AlterModelOptions(
            name='type_event',
            options={'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы событий'},
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 10, 11), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 10, 11), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 10, 11), verbose_name='Дата'),
        ),
    ]
