# Generated by Django 2.2.6 on 2022-11-30 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0045_auto_20221129_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='th',
            name='type_th',
            field=models.TextField(blank=True, null=True, verbose_name='Вх. / Исх.'),
        ),
        migrations.AddField(
            model_name='th',
            name='year',
            field=models.TextField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 11, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='num',
            field=models.TextField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 11, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2022, 11, 30), verbose_name='Дата'),
        ),
    ]
