# Generated by Django 2.2.6 on 2023-04-25 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0061_auto_20230424_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('number',), 'verbose_name': 'Учетная еденица', 'verbose_name_plural': 'Учетные еденицы'},
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 4, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 4, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер учетный'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 4, 25), verbose_name='Дата'),
        ),
    ]
