# Generated by Django 2.2.6 on 2023-05-10 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0062_auto_20230425_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('-number',), 'verbose_name': 'Учетная еденица', 'verbose_name_plural': 'Учетные еденицы'},
        ),
        migrations.AddField(
            model_name='th',
            name='unit_number',
            field=models.TextField(blank=True, null=True, verbose_name='номер уч. ед.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='event',
            name='num',
            field=models.TextField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 5, 10), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 5, 10), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to='storage.Creator', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ctgry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctgrys', to='storage.Ctgry', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='storage.Place', verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 5, 10), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='stend',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stends', to='storage.Stend', verbose_name='Стенд'),
        ),
    ]
