# Generated by Django 2.2.6 on 2023-08-17 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0071_auto_20230808_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='acctual',
            field=models.BooleanField(blank=True, null=True, verbose_name='Данные актуальны'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 8, 17), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 8, 17), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2023, 8, 17), verbose_name='Дата'),
        ),
    ]
