# Generated by Django 2.2.6 on 2022-10-18 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corresp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Номер')),
                ('in_out', models.TextField(verbose_name='Вх/Исх')),
                ('company', models.TextField(verbose_name='компания')),
                ('from_who', models.TextField(verbose_name='От кого')),
                ('to', models.TextField(verbose_name='Кому')),
                ('day', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='формат ввода: YYYY-mm-dd', null=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField(verbose_name='Кто добавил')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'verbose_name_plural': 'Корреспонденция',
                'ordering': ('number',),
            },
        ),
    ]
