# Generated by Django 2.2.6 on 2022-10-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirr', models.CharField(max_length=50, verbose_name='Направление')),
            ],
            options={
                'ordering': ('dirr',),
            },
        ),
        migrations.AlterField(
            model_name='corresp',
            name='company',
            field=models.TextField(verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='correspondence/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='in_out',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_out_dirr', to='corresp.In_out', verbose_name='Вх/Исх'),
        ),
    ]
