# Generated by Django 2.2.6 on 2022-10-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0002_auto_20221018_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'ordering': ('cor_type',),
            },
        ),
        migrations.AddField(
            model_name='corresp',
            name='cor_type',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cor_types', to='corresp.Type', verbose_name='Тип'),
        ),
    ]
