# Generated by Django 2.2.6 on 2022-10-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0003_auto_20221019_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresp',
            name='cor_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cor_types', to='corresp.Type', verbose_name='Тип'),
        ),
    ]
