# Generated by Django 2.2.6 on 2022-10-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0004_auto_20221019_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=200, verbose_name='автор/адресант')),
            ],
            options={
                'ordering': ('who',),
            },
        ),
        migrations.AlterField(
            model_name='corresp',
            name='from_who',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_whos', to='corresp.Who', verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='in_out',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_out_dirr', to='corresp.In_out', verbose_name='Вх/Исх'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='to',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_whos', to='corresp.Who', verbose_name='Кому'),
        ),
    ]
