# Generated by Django 2.2.6 on 2023-02-20 12:02

import corresp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0005_auto_20221019_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresp',
            name='company',
            field=models.TextField(blank=True, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=corresp.models.get_path, verbose_name='Документ'),
        ),
    ]
