# Generated by Django 2.2.6 on 2024-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0006_auto_20230220_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corresp',
            options={'ordering': ('day',), 'verbose_name': 'Корреспонденция', 'verbose_name_plural': 'Корреспонденция'},
        ),
        migrations.AddField(
            model_name='corresp',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Кто добавил'),
        ),
        migrations.AlterField(
            model_name='corresp',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
